In [1]:
import pandas as pd

In [2]:
#concatination,join operation,merge operation and some numerical computations with the help of numpy

In [3]:
data= { "name": ["sudh", "krish", "hitesh", "tulesko"], 
       "salary": [100,200,300,400],
       "mail_id": ["sudh@ineuron.ai", "krish@ineuron.ai", "hitesh@ineuron.ai","tulesko@ineuron.ai"],
       "addr" : ["blr", "blr", "blr", "mum"]
    }

In [4]:
pd.DataFrame(data)

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [5]:
#length jodi soman na thake tahole issue dekhabe dataframe toiri korbena
datag= { "name": ["sudh", "krish", "hitesh", "tulesko", "hhh"], 
       "salary": [100,200,300,400],
       "mail_id": ["sudh@ineuron.ai", "krish@ineuron.ai", "hitesh@ineuron.ai","tulesko@ineuron.ai"],
       "addr" : ["blr", "blr", "blr", "mum"]
    }

In [6]:
pd.DataFrame(datag)

ValueError: All arrays must be of the same length

In [ ]:
#giving own column name
pd.DataFrame(data, columns=[0,1,2,3])
#dataframe didnt include new column, jodi main data frame key and value hoy tahole eti kono redundant accept korbena

In [7]:
pd.DataFrame(data, index=[4,5,6,7])
#giving own index name

name  salary             mail_id addr
4     sudh     100     sudh@ineuron.ai  blr
5    krish     200    krish@ineuron.ai  blr
6   hitesh     300   hitesh@ineuron.ai  blr
7  tulesko     400  tulesko@ineuron.ai  mum

In [8]:
#extracting rows
df=pd.DataFrame(data, index=[4,5,6,7])

In [9]:
df

name  salary             mail_id addr
4     sudh     100     sudh@ineuron.ai  blr
5    krish     200    krish@ineuron.ai  blr
6   hitesh     300   hitesh@ineuron.ai  blr
7  tulesko     400  tulesko@ineuron.ai  mum

In [10]:
df.loc [5:6]

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [11]:
df.iloc[5:6]
#no data , bcz iloc goes with default indexes, nam dite hobe, ja amr ase

Empty DataFrame
Columns: [name, salary, mail_id, addr]
Index: []

In [12]:
df.iloc[1:3]

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [13]:
#giving raw index er new string name
df = pd.DataFrame(data, index =["sudh", "krish", "hite", "tule"])

In [14]:
df

name  salary             mail_id addr
sudh      sudh     100     sudh@ineuron.ai  blr
krish    krish     200    krish@ineuron.ai  blr
hite    hitesh     300   hitesh@ineuron.ai  blr
tule   tulesko     400  tulesko@ineuron.ai  mum

In [15]:
df = pd.DataFrame(data)

In [16]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [17]:
data1= {'pf_nu' : [234,45,54465,656],
        'income_tax' : [234,565,767,6778],
        'mobile_no' : [23543,43543,454,5656],
        'courses' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [18]:
df1 = pd.DataFrame(data1)

In [19]:
df1

pf_nu  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454    web dev 
3    656        6778       5656  blockchian

In [20]:
#concatenation operation between two dataframe , normally + diye kora hoy
"""concatenatinate vertically or horizontally kora jay"""

'concatenatinate vertically or horizontally kora jay'

In [21]:
pd.concat([df,df1])
#horizontal concatenation, 

name  salary             mail_id addr    pf_nu  income_tax  mobile_no  \
0     sudh   100.0     sudh@ineuron.ai  blr      NaN         NaN        NaN   
1    krish   200.0    krish@ineuron.ai  blr      NaN         NaN        NaN   
2   hitesh   300.0   hitesh@ineuron.ai  blr      NaN         NaN        NaN   
3  tulesko   400.0  tulesko@ineuron.ai  mum      NaN         NaN        NaN   
0      NaN     NaN                 NaN  NaN    234.0       234.0    23543.0   
1      NaN     NaN                 NaN  NaN     45.0       565.0    43543.0   
2      NaN     NaN                 NaN  NaN  54465.0       767.0      454.0   
3      NaN     NaN                 NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [22]:
pd.concat([df,df1], axis=1)
#now its a complete horizontal concatenation , 
# raw index is same but column name is different then ei doroner concatenate hoy, axis =1 means column wise concatenation
"""two dataframe , or more excel or dataframe is related data set eivabe concatenate korte pari"""

'two dataframe , or more excel or dataframe is related data set eivabe concatenate korte pari'

In [23]:
data2 = {'0' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'],
        '1' : [100 , 200 , 300 , 400],
        '2' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        '3' : ['blr' , 'blr' , 'blr' , 'mum']
    }

In [24]:
data3= {'0' : [234,45,54465,656],
        '1' : [234,565,767,6778],
        '2' : [23543,43543,454,5656],
        '3' : ['blr' , 'blr' , 'blr' , 'mum'],
        '3' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [25]:
df2 = pd.DataFrame(data2)

In [26]:
df3 = pd.DataFrame(data3)

In [27]:
df2

0    1                   2    3
0     sudh  100     sudh@ineuron.ai  blr
1    krish  200    krish@ineuron.ai  blr
2   hitesh  300   hitesh@ineuron.ai  blr
3  tulesko  400  tulesko@ineuron.ai  mum

In [28]:
df3

0     1      2           3
0    234   234  23543          ds
1     45   565  43543     bigdata
2  54465   767    454    web dev 
3    656  6778   5656  blockchian

In [29]:
pd.concat([df2, df3])
#vertical concatenate, if column name is same then complete vertical concatenate hoy

0     1                   2           3
0     sudh   100     sudh@ineuron.ai         blr
1    krish   200    krish@ineuron.ai         blr
2   hitesh   300   hitesh@ineuron.ai         blr
3  tulesko   400  tulesko@ineuron.ai         mum
0      234   234               23543          ds
1       45   565               43543     bigdata
2    54465   767                 454    web dev 
3      656  6778                5656  blockchian

In [30]:
#Merge operatuion, merge concatenation theke ektu different

In [31]:
data4 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }

In [32]:
data5  = {'emp_id' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
    
}

In [33]:
df4 = pd.DataFrame(data4)

In [34]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [35]:
df5 = pd.DataFrame(data5)

##### 

In [36]:
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [37]:
"""if two dataframe are related somehow , and realtionship by employee id
"""

'if two dataframe are related somehow , and realtionship by employee id\n'

In [38]:
#merge operation and join operation


#merge right and lefet and by default inner join, first one is left and second one is right parameter

how: inner join by default, and inner join 2 ta dataframe er modde common data niye mergekore

    on: index level, if there no common it will not even merge

    
    
    
    

In [39]:
#pandas merge operation

In [43]:
pd.merge(df4,df5)
#inner merge by deafalut
#"""two data frame are related by common value  """

emp_id  salary  pf  mob_no  house_nu
0     101     234  23    3434       345
1     102     345  34    5656       345
2     104     400  78     767       345

In [41]:
pd.merge(df4,df5, how= "left")
#left merge

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [ ]:
pd.merge(df4,df5, how= "left")
#right merge

In [44]:
pd.merge(df4,df5, how= "right", on ="emp_id")
#which column will create relation in dataframes, mentioning that by on

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [ ]:
#new data frame

In [45]:
data6 = {'emp_id1' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data7  = {'emp_id2' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
    
}

In [47]:
df6 = pd.DataFrame(data6)

In [48]:
df7= pd.DataFrame(data7)

In [49]:
df6

emp_id1  salary  pf
0      101     234  23
1      102     345  34
2      103     200  56
3      104     400  78

In [50]:
df7

emp_id2  mob_no  house_nu
0      101    3434       345
1      102    5656       345
2      104     767       345
3      105     878        56

In [53]:
pd.merge (df6 , df7 )
#merge with different column name within dataframe, jehetu column name different tai error show korbe , but amra tarpor oo merge korte pari, niche system e

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [56]:
pd.merge(df6,df7, left_on="emp_id1", right_on= "emp_id2")

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [ ]:
#Merging two different dataframe by comparing reltion of two column at a time 
#here two relational columns are emp_id and salary

In [57]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data9  = {'emp_id' : [101,102,104,105,123],
          'salary' : [234, 345,200,878,43],
          'house_nu' : [345,345,345,56,234]
    
}

In [59]:

df8= pd.DataFrame(data8)

In [60]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [61]:
df9= pd.DataFrame(data9)

In [62]:
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     878        56
4     123      43       234

In [63]:
#here two relational columns are emp_id and salary
pd.merge(df8,df9, on=["emp_id","salary"])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [ ]:
#dimension also kono problem create korena, ektar boro arektar suto 

In [64]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data9  = {'emp_id' : [101,102,104,105,123],
          'salary' : [234, 345,200,878,43],
          'house_nu' : [345,345,345,56,234]
    
}

In [69]:
df8 = pd.DataFrame(data8)

In [68]:
df9 = pd.DataFrame(data9)

In [70]:
pd.merge(df8, df9)

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [ ]:
#how joins are different from merge operation , and how join can use for any situations

In [71]:
data10 = {'emp_id1' : [101,102,103,104],
         'salary1' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data11  = {'emp_id2' : [101,102,104,105,123],
          'salary2' : [234, 345,200,878,43],
          'house_nu' : [345,345,345,56,234]
    
}

In [72]:
df10 = pd.DataFrame(data10,index=['a' ,'b','c' ,'d'])

In [73]:
df11 = pd.DataFrame(data11,index=['a','b','d','e','f'])

In [74]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

# 

In [75]:
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
d      104      200       345
e      105      878        56
f      123       43       234

In [79]:
df10.join(df11)
#merge and join both are same, but join works based on raw indexes and merge works based on column name that u have given

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [81]:
df_sales  = pd.read_csv("sales_data_final.csv")

In [82]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [ ]:
#creating new column to store data from another existing column

In [85]:
def profit_flag(a):
    if a >= 0:
        return "positive"
    else:
        return "negative"

In [86]:
profit_flag (-45)

'negative'

In [87]:
df_sales["flag_profit"]= df_sales["profit"].apply(profit_flag)

In [88]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    positive  
1           9.72          Medium  2011    positive  
2           8.17            High  2011    positive  
3           4.82            High  2011    negative  
4           4.70          Medium  2011    positive  

[5 rows x 22 columns]

In [ ]:
#creating new column to store length of the customer name

In [89]:
df_sales['len_cust_name'] = df_sales['customer_name'].apply(len)

In [90]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_profit len_cust_name  
0          35.46          Medium  2011     positive            15  
1           9.72          Medium  2011     positive            11  
2           8.17            High  2011     positive            13  
3           4.82            High  2011     negative            12  
4           4.70          Medium  2011     positive            11  

[5 rows x 23 columns]

In [ ]:
#deriving column: catagorize data from a column into 3 segments, like high , low and medium

In [91]:
def quantity_flag(a):
    if a<10 :
        return "low"
    elif a> 10 and a<20:
        return "medium"
    else :
        return "high"

In [94]:
df_sales["flag_quantity"]=df_sales["quantity"].apply(quantity_flag)

In [98]:
df_sales.head(5)

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  flag_profit  \
0        2      0.0  106.140         35.46          Medium  2011     positive   
1        3      0.1   36.036          9.72          Medium  2011     positive   
2        4      0.0   29.640          8.17            High  2011     positive   
3        3      0.5  -26.055          4.82            High  2011     negative   
4        5      0.1   37.770          4.70          Medium  2011     positive   

   len_cust_name flag_quantity  
0             15           low  
1             11           low  
2             13           low  
3             12           low  
4             11           low  

[5 rows x 24 columns]

In [ ]:
#deriving column based on lemda functiond
#line anonymus function, we can create function in one line

In [99]:
df_sales["square_quantity"]=df_sales["quantity"].apply(lambda a:a**2)

In [100]:
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ... quantity discount    profit shipping_cost order_priority  \
0       Africa  ...        2      0.0  106.1400         35.46         Medium   
1      Oceania  ...        3      0.1   36.0360          9.72         Medium   
2         EMEA  ...        4      0.0   29.6400          8.17           High   
3        North  ...        3      0.5  -26.0550          4.82           High   
4      Oceania  ...        5      0.1   37.7700          4.70         Medium   
...        ...  ...      ...      ...       ...           ...            ...   
51285     West  ...        2      0.2    4.5188          0.89         Medium   
51286   Africa  ...        1      0.0    0.4200          0.49         Medium   
51287  Central  ...        3      0.0   12.3600          0.35         Medium   
51288    North  ...        1      0.0    0.5600          0.20         Medium   
51289     West  ...        3      0.2   -0.6048          0.17         Medium   

       year  flag_profit  len_cust_name  flag_quantity square_quantity  
0      2011     positive             15            low               4  
1      2011     positive             11            low               9  
2      2011     positive             13            low              16  
3      2011     negative             12            low               9  
4      2011     positive             11            low              25  
...     ...          ...            ...            ...             ...  
51285  2014     positive             10            low               4  
51286  2014     positive              9            low               1  
51287  2014     positive             16            low               9  
51288  2014     positive             13            low               1  
51289  2014     negative             13            low               9  

[51290 rows x 25 columns]

In [101]:
df_sales["total_revenue"]=df_sales["quantity"]*df_sales["profit"]

In [102]:
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ... discount    profit shipping_cost order_priority  year  \
0       Africa  ...      0.0  106.1400         35.46         Medium  2011   
1      Oceania  ...      0.1   36.0360          9.72         Medium  2011   
2         EMEA  ...      0.0   29.6400          8.17           High  2011   
3        North  ...      0.5  -26.0550          4.82           High  2011   
4      Oceania  ...      0.1   37.7700          4.70         Medium  2011   
...        ...  ...      ...       ...           ...            ...   ...   
51285     West  ...      0.2    4.5188          0.89         Medium  2014   
51286   Africa  ...      0.0    0.4200          0.49         Medium  2014   
51287  Central  ...      0.0   12.3600          0.35         Medium  2014   
51288    North  ...      0.0    0.5600          0.20         Medium  2014   
51289     West  ...      0.2   -0.6048          0.17         Medium  2014   

       flag_profit  len_cust_name  flag_quantity  square_quantity  \
0         positive             15            low                4   
1         positive             11            low                9   
2         positive             13            low               16   
3         negative             12            low                9   
4         positive             11            low               25   
...            ...            ...            ...              ...   
51285     positive             10            low                4   
51286     positive              9            low                1   
51287     positive             16            low                9   
51288     positive             13            low                1   
51289     negative             13            low                9   

      total_revenue  
0          212.2800  
1          108.1080  
2          118.5600  
3          -78.1650  
4          188.8500  
...             ...  
51285        9.0376  
51286        0.4200  
51287       37.0800  
51288        0.5600  
51289       -1.8144  

[51290 rows x 26 columns]

In [ ]:
#Numpy : for numericl calculation numpy libraray

#for  EDA we use  pandas, numpy, plotly,cuplings, seaborn
#Data analysis is accomplished by using these 4-5 libraries
#EDA is just trying to find meaningful data

In [ ]:
#Numpy (numerical python)
#Matlob(a tool design,mathemetical operation, numerical operation, neural operation) is converted to numpy

#mulitple merical operation, matrix,arrays
# for machine learning, dl, analytic we use tensorflow, pytorch, ongnx, all of these deived from core numpy library
#all files like excel , csv, json comes as array or matrix into system





In [104]:
import numpy as np

In [ ]:
#Array
#


In [105]:
np.array([2,3,4,5,6])
#whatever list i write , it is giving as array

array([2, 3, 4, 5, 6])

In [106]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [107]:
np.array([[2,3,4],[4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [ ]:
#visualize array
#row is presented by y axis and column in x axis
#by deafault dimension of a array is 1 dimension is written ndmin

In [108]:
np.array([[1,2,3,4] , [ 2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [109]:
l = [[1,2,3,4] , [ 2,3,4,5]]

In [115]:
a=np.array([3,4,5,6],ndmin=3)

In [114]:
a

array([[[[[3, 4, 5, 6]]]]])

In [116]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

In [117]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
arr.ndim
#to see a dimension of array by ndim

2

In [120]:
np.random.randint(1,10,(4,4))
#showing 3d array, how 3d dimensional array look like
#np.random.randint: this funciton is used to create random number in numpy
#1,10 hosse range where number will b created
#dimension 4,4 means 4 raws and 4 columns
#two square bracket = 2 dimension

array([[2, 1, 5, 8],
       [9, 4, 7, 9],
       [9, 7, 6, 3],
       [4, 7, 3, 2]])

In [121]:
np.random.randint(1,10,(4,4,2))

array([[[5, 5],
        [3, 1],
        [4, 1],
        [1, 9]],

       [[9, 1],
        [5, 9],
        [6, 7],
        [2, 3]],

       [[7, 7],
        [5, 6],
        [7, 5],
        [3, 6]],

       [[8, 1],
        [8, 1],
        [7, 3],
        [3, 9]]])